

- name: Add python repository
  apt_repository:
    repo:  ppa:deadsnakes/ppa
    state: present
    update_cache: yes

- name: install python 3.6
  apt: 
    name: python3.6
    state: present 


- name: install pip3
  apt: 
    name: python3-pip 
    state: present 

- name: Install Virtual ENV
  pip:
    name: virtualenv
    state: present