apiVersion: v1
kind: Service
metadata:
  name: dev-v3-nginx
spec:
  selector:
    cht.service: dev-v3-nginx
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30081