apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cht.service: dev-v3-medic-data
    app: dev-v3
  name: dev-v3-medic-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
status: {}