---
- name: Make sure the Courier group exists
  group:
    name: "{{ courier_system_group }}"
    state: present

- name: Make sure the Courier user exists
  user:
    name: "{{ courier_system_user }}"
    group: "{{ courier_system_group }}"
    home: "{{ courier_system_home }}"
    shell: /bin/nologin

- name: Make sure the package directory exists
  file:
    name: "{{ courier_package_directory_path }}"
    state: directory
    owner: "{{ courier_system_user }}"
    group: "{{ courier_system_group }}"
    mode: 0755

- name: Download Courier
  unarchive:
    src: "{{ courier_download_url }}"
    dest: "{{ courier_package_directory_path }}"
    remote_src: true
    owner: "{{ courier_system_user }}"
    group: "{{ courier_system_group }}"
    mode: 0755

- name: Make the installed version current
  file:
    force: true
    state: link
    src: "{{ courier_package_directory_path }}"
    dest: "{{ courier_active_package_symlink }}"
    owner: "{{ courier_system_user }}"
    group: "{{ courier_system_group }}"
  notify:
    - restart courier
