---
- name: Make sure the RapidPro Indexer group exists
  group:
    name: "{{ rapidpro_indexer_system_group }}"
    state: present

- name: Make sure the RapidPro Indexer user exists
  user:
    name: "{{ rapidpro_indexer_system_user }}"
    group: "{{ rapidpro_indexer_system_group }}"
    home: "{{ rapidpro_indexer_system_home }}"
    shell: /bin/nologin

- name: Make sure the package directory exists
  file:
    name: "{{ rapidpro_indexer_package_directory_path }}"
    state: directory
    owner: "{{ rapidpro_indexer_system_user }}"
    group: "{{ rapidpro_indexer_system_group }}"
    mode: 0755

- name: Download RapidPro Indexer
  unarchive:
    src: "{{ rapidpro_indexer_download_url }}"
    dest: "{{ rapidpro_indexer_package_directory_path }}"
    remote_src: true
    owner: "{{ rapidpro_indexer_system_user }}"
    group: "{{ rapidpro_indexer_system_group }}"
    mode: 0755

- name: Make the installed version current
  file:
    force: true
    state: link
    src: "{{ rapidpro_indexer_package_directory_path }}"
    dest: "{{ rapidpro_indexer_active_package_symlink }}"
    owner: "{{ rapidpro_indexer_system_user }}"
    group: "{{ rapidpro_indexer_system_group }}"
  notify:
    - restart rapidpro-indexer
