---
- name: Copy the Mailroom environment file
  template:
    src: "mailroom_active_package_symlink/environment.j2"
    dest: "{{ mailroom_active_package_symlink }}/environment"
    owner: "{{ mailroom_system_user }}"
    group: "{{ mailroom_system_group }}"
    mode: 0750
  notify:
    - restart mailroom

- name: Copy the Mailroom systemd unit File
  template:
    src: "etc/systemd/system/mailroom_service_name.service.j2"
    dest: "/etc/systemd/system/{{ mailroom_service_name }}.service"
  notify:
    - restart mailroom
