---
- name: Make sure the RapidPro Archiver group exists
  group:
    name: "{{ rapidpro_archiver_system_group }}"
    state: present

- name: Make sure the RapidPro Archiver user exists
  user:
    name: "{{ rapidpro_archiver_system_user }}"
    group: "{{ rapidpro_archiver_system_group }}"
    home: "{{ rapidpro_archiver_system_home }}"
    shell: /bin/nologin

- name: Make sure the package directory exists
  file:
    name: "{{ rapidpro_archiver_package_directory_path }}"
    state: directory
    owner: "{{ rapidpro_archiver_system_user }}"
    group: "{{ rapidpro_archiver_system_group }}"
    mode: 0755

- name: Download RapidPro Archiver
  unarchive:
    src: "{{ rapidpro_archiver_download_url }}"
    dest: "{{ rapidpro_archiver_package_directory_path }}"
    remote_src: true
    owner: "{{ rapidpro_archiver_system_user }}"
    group: "{{ rapidpro_archiver_system_group }}"
    mode: 0755

- name: Make the installed version current
  file:
    force: true
    state: link
    src: "{{ rapidpro_archiver_package_directory_path }}"
    dest: "{{ rapidpro_archiver_active_package_symlink }}"
    owner: "{{ rapidpro_archiver_system_user }}"
    group: "{{ rapidpro_archiver_system_group }}"
  