- name: Create a ext4 filesystem on volume
  become: yes
  filesystem:
    force: no
    fstype: ext4
    dev:  "{{volume_path}}"

- name: Mount Volume to mount path
  become: yes
  mount:
    path: "{{mount_path}}"
    src: "{{volume_path}}"
    fstype: "{{file_system_type}}"
    state: mounted